=== aczepod/PHPWrapper/defines/Ontology.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    
    <!-- ROOT -->
    <xs:element name="ONTOLOGY">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The ontology is an element container for the list of units.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="UNIT" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- UNIT -->
    <xs:element name="UNIT">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Each unit represents a set of term, node, edge and tag
                instances which define a set of graph related elements.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="TERM">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            List of terms to be instantiated.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="NODE">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            List of nodes to be instantiated.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="EDGE">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            List of edges to be instantiated.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="TAG">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            List of tags to be instantiated.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- TERMS -->
    <xs:element name="TERM">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Term block, should instantiate a single block and can be
                repeated for as many terms need to be defined for the curent block.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="element"/>
            </xs:sequence>
            <xs:attribute name="GID" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Term global identifier, used to reference the term.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="LID" use="required" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Term local identifier.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="NS" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Term namespace as the namespace's term global identifier.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <!-- NODES -->
    <xs:element name="NODE">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Node block, should instantiate a single block and can be
                repeated for as many nodes need to be defined for the curent block.
                Nodes will be identified within the block by the term identifier:
                this means that no two nodes may refer to a term in the same unit.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="element"/>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:ID">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Node identifier, allows referencing homonym term nodes;
                        this attribute has nothing to do with the actual node ID.
                        Use this attribute only if two nodes refer to the same term,
                        or if the node to be referenced is not the node in the current unit.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="class" use="required" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Node class name, this attribute is required.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="term" use="required" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Term reference, should refer to the global identifier of the term.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <!-- EDGES -->
    <xs:element name="EDGE">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Edge block, should instantiate a single relationship and can be
                repeated for as many edges need to be defined for the curent block.
                Nodes are referenced by their term global identifier, as stated above,
                no two nodes may refer to the same term within the same unit.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="element"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- TAGS -->
    <xs:element name="TAG">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Tag block, should instantiate a single tag, elements of the kTAG_PATH
                must be referenced by term global identifier: if any matching node was instantiated
                within the unit, it will be used instead of the term.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="element"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Attributes -->
    <xs:element name="element">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Attribute block, each element should define a single property
                or attribute. Array elements should include item elements, scalar
                elements should store the value.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="item"/>
            </xs:sequence>
            <xs:attribute name="tag" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The tag attribute should reference a tag native identifier.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="variable" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The variable attribute should reference a tag through the
                        constant name.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <!-- Attribute items -->
    <xs:element name="item">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Item elements should be used to instantiate array elements,
                use the key attribute if the array uses keys.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="item"/>
            </xs:sequence>
            <xs:attribute name="key" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        This attribute should hold the array item index value, only
                        if the array is to be used as an object.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aczepod/PHPWrapper/data/Default Ontology/Namespaces.xml
<?xml version="1.0" encoding="UTF-8"?>
<ONTOLOGY
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Library/WebServer/Library/PHPWrapper/defines/Ontology.xsd">
    
    <!-- Namespaces -->
    
    <UNIT>
		<!-- Default namespace -->
        <TERM LID="">
            <element variable="kTAG_KIND">
                <item>:KIND-NAMESPACE</item>
            </element>
            <element variable="kTAG_LABEL">
                <item key="en">Default namespace</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[This <i>namespace</i> groups all default terms of the ontology, these are the elements that will be used to build the ontology itself.]]></item>
            </element>
        </TERM>
    
		<!-- Status namespace -->
        <TERM NS="" LID="STATUS">
            <element variable="kTAG_KIND">
                <item>:KIND-NAMESPACE</item>
            </element>
            <element variable="kTAG_LABEL">
                <item key="en">Status</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[This <i>namespace</i> groups all terms which define a <i>status level</i> or <i>type</i>.]]></item>
            </element>
        </TERM>
    </UNIT>
 </ONTOLOGY>

=== aczepod/PHPWrapper/data/Default Ontology/Edge.xml
<?xml version="1.0" encoding="UTF-8"?>
<ONTOLOGY
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Library/WebServer/Library/PHPWrapper/defines/Ontology.xsd">
    
    <!-- Edge object -->
    
    <UNIT>
        <TERM NS="" LID="_edges">
            <element variable="kTAG_LABEL">
                <item key="en">Edge</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[An ontology edge <i>relates ontology nodes</i> via a predicate. Edges are represented by a triplet: <i>subject</i>, <i>predicate</i> and <i>object</i>, in which the subject and the object are ontology nodes and the predicate is an ontology term.]]></item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
            <element variable="kTAG_CATEGORY">
                <item>Schema</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:OBJECT</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_NID -->
    <UNIT>
        <NODE class="COntologyAliasVertex" term=":NID">
            <element variable="kTAG_PID">:_edges.:NID</element>
            <element variable="kTAG_KIND">
                <item>:KIND-FEATURE</item>
                <item>:KIND-SCALE</item>
            </element>
            <element variable="kTAG_TYPE">
                <item>:INT</item>
                <item>:COMPUTED</item>
                <item>:REQUIRED</item>
            </element>
            <element variable="kTAG_DESCRIPTION">
                <item key="en"><![CDATA[The <i>native identifier</i> of an edge is an <i>integer</i> <i>generated by a sequence</i> or <i>taken from a created graph edge identifier</i>.]]></item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_edges</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_GID -->
    <UNIT>
        <NODE class="COntologyAliasVertex" term=":GID">
            <element variable="kTAG_PID">:_edges.:NID</element>
            <element variable="kTAG_KIND">
                <item>:KIND-FEATURE</item>
                <item>:KIND-SCALE</item>
            </element>
            <element variable="kTAG_TYPE">
                <item>:TEXT</item>
                <item>:LOCKED</item>
                <item>:COMPUTED</item>
                <item>:REQUIRED</item>
            </element>
            <element variable="kTAG_DESCRIPTION">
                <item key="en"><![CDATA[The <i>global identifier</i> of an edge is computed by <i>concatenating</i> the <i>subject vertex native identifier</i>, the <i>predicate global identifier</i> and the <i>object vertex native identifier</i> separated by a slash.]]></item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_edges</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_CLASS -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:CLASS</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_edges</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_UID -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:UID</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_edges</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_SUBJECT -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:SUBJECT</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_edges</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_PREDICATE -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:PREDICATE</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_edges</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_OBJECT -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:OBJECT</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_edges</element>
        </EDGE>
    </UNIT>
</ONTOLOGY>

=== aczepod/PHPWrapper/scrapbook/OntologyTest1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ONTOLOGY
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://standards.grinfo.net/schema/Ontology.xsd">
    
    <UNIT>
        <TERM GID="localId0" LID="localId0">
            <element tag="tag0">
                <item>Uno</item>
                <item>Due</item>
                <item>Tre</item>
            </element>
            <element tag="tag1">pippo</element>
            <element variable="kTAG_PIPPO">
                <item key="key6">baba</item>
                <item key="key7">bibi</item>
                <item key="key8">bobo</item>
            </element>
        </TERM>
        <NODE Class="COntologyMasterVertex" Term="localId0">
            <element variable="kTAG_KIND">
                <item>:FEATURE</item>
                <item>:SCALE</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_SUBJECT">localID0</element>
            <element variable="kTAG_PREDICATE">:ENUM-OF</element>
            <element variable="kTAG_OBJECT">localID0</element>
        </EDGE>
        <TAG>
            <element variable="kTAG_PATH">
                <item>localId:FEATURE</item>
                <item>localId:PREDICATE</item>
                <item>localId:SCALE</item>
            </element>
        </TAG>
    </UNIT>
    <UNIT>
        <TERM GID="localId0" LID="localId0">
            <element variable="kTAG_LABEL">
                <item key="en">One</item>
                <item key="it">Uno</item>
                <item key="fr">Un</item>
            </element>
            <element variable="kTAG_PATTERN"><![CDATA[[A-Za-z0-9]+]]></element>
            <element variable="kTAG_KIND">
                <item>baba</item>
                <item>bibi</item>
                <item>bobo</item>
            </element>
        </TERM>
        <TERM GID="nameSpace1:localId1" NS="nameSpace1" LID="localId1">
            <element tag="tag3">
                <item key="key9">baba</item>
                <item key="key10">
                    <item>haha</item>
                    <item>jaja</item>
                </item>
                <item key="key11">xexe</item>
            </element>
            <element tag="tag4">
                <item>baba</item>
                <item>
                    <item key="key9">haha</item>
                    <item key="key10">jaja</item>
                </item>
                <item>xexe</item>
            </element>
            <element tag="tag5">
                <item key="key9">baba</item>
                <item key="key10">
                    <item key="key10">haha</item>
                    <item key="key11">jaja</item>
                </item>
                <item key="key11">xexe</item>
            </element>
            <element>
                <item>baba</item>
                <item>
                    <item>haha</item>
                    <item>jaja</item>
                </item>
                <item>xexe</item>
            </element>
        </TERM>
    </UNIT>
</ONTOLOGY>

=== aczepod/PHPWrapper/data/Default Ontology/Tag.xml
<?xml version="1.0" encoding="UTF-8"?>
<ONTOLOGY
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Library/WebServer/Library/PHPWrapper/defines/Ontology.xsd">
    
    <!-- Tag object -->
    
    <UNIT>
        <TERM NS="" LID="_tags">
            <element variable="kTAG_LABEL">
                <item key="en">Tag</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[An ontology tag represents the <i>path</i> between an <i>ontology feature vertex</i> and an <i>ontology scale vertex</i>. Tags record the terms referenced by the vertices and the predicates that relate them.]]></item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
            <element variable="kTAG_CATEGORY">
                <item>Schema</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:OBJECT</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_NID -->
    <UNIT>
        <NODE class="COntologyAliasVertex" term=":NID">
            <element variable="kTAG_KIND">
                <item>:KIND-FEATURE</item>
                <item>:KIND-SCALE</item>
            </element>
            <element variable="kTAG_TYPE">
                <item>:INT</item>
                <item>:COMPUTED</item>
                <item>:REQUIRED</item>
            </element>
            <element variable="kTAG_DESCRIPTION">
                <item key="en"><![CDATA[The <i>native identifier</i> of a tag is an <i>integer</i> <i>generated by a sequence</i>. <i>All the attributes in this system are tagged with this attribute</i>, this is why it must be short.]]></item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_tags</element>
        </EDGE>
    </UNIT>
     
	<!-- kTAG_GID -->
    <UNIT>
        <NODE class="COntologyAliasVertex" term=":GID">
            <element variable="kTAG_KIND">
                <item>:KIND-FEATURE</item>
                <item>:KIND-SCALE</item>
            </element>
            <element variable="kTAG_TYPE">
                <item>:TEXT</item>
                <item>:LOCKED</item>
                <item>:COMPUTED</item>
                <item>:REQUIRED</item>
            </element>
            <element variable="kTAG_DESCRIPTION">
                <item key="en"><![CDATA[The <i>global identifier</i> of a tag is computed by <i>concatenating</i> the <i>term global identifiers</i> of all the <i>elements of the tag's path</i>, <i>separated by a slash</i>.]]></item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_tags</element>
        </EDGE>
    </UNIT>
   
	<!-- kTAG_CLASS -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:CLASS</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_tags</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_UID -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:UID</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_tags</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_PATH -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:PATH</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_tags</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_SYNONYMS -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:SYNONYMS</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_tags</element>
        </EDGE>
    </UNIT>
        
	<!-- kTAG_INPUT -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:INPUT</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_nodes</element>
        </EDGE>
    </UNIT>
        
	<!-- kTAG_PATTERN -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:PATTERN</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_nodes</element>
        </EDGE>
    </UNIT>
        
	<!-- kTAG_LENGTH -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:LENGTH</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_nodes</element>
        </EDGE>
    </UNIT>
        
	<!-- kTAG_MIN_VAL -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:MIN-VAL</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_nodes</element>
        </EDGE>
    </UNIT>
        
	<!-- kTAG_MAX_VAL -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:MAX-VAL</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_nodes</element>
        </EDGE>
    </UNIT>
        
	<!-- kTAG_EXAMPLES -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:EXAMPLES</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_nodes</element>
        </EDGE>
    </UNIT>
</ONTOLOGY>

=== aczepod/PHPWrapper/data/Default Ontology/User.xml
<?xml version="1.0" encoding="UTF-8"?>
<ONTOLOGY
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Library/WebServer/Library/PHPWrapper/defines/Ontology.xsd">
    
    <!-- User object -->
    
    <UNIT>
        <TERM NS="" LID="_users">
            <element variable="kTAG_LABEL">
                <item key="en">User</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[Users collect all information specific to the system users.]]></item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
            <element variable="kTAG_CATEGORY">
                <item>Schema</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:OBJECT</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_NID -->
    <UNIT>
        <NODE class="COntologyAliasVertex" term=":NID">
            <element variable="kTAG_PID">:_users.:NID</element>
            <element variable="kTAG_KIND">
                <item>:KIND-FEATURE</item>
                <item>:KIND-SCALE</item>
            </element>
            <element variable="kTAG_TYPE">
                <item>:BINARY</item>
                <item>:COMPUTED</item>
                <item>:REQUIRED</item>
            </element>
            <element variable="kTAG_DESCRIPTION">
                <item key="en"><![CDATA[The <i>native identifier</i> of a user is its <i>global identifier hashed</i> into a binary string.]]></item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_GID -->
    <UNIT>
        <NODE class="COntologyAliasVertex" term=":GID">
            <element variable="kTAG_PID">:_users.:GID</element>
            <element variable="kTAG_KIND">
                <item>:KIND-FEATURE</item>
                <item>:KIND-SCALE</item>
            </element>
            <element variable="kTAG_TYPE">
                <item>:TEXT</item>
                <item>:LOCKED</item>
                <item>:COMPUTED</item>
                <item>:REQUIRED</item>
            </element>
            <element variable="kTAG_INPUT">
                <item>:INPUT-TEXT</item>
            </element>
            <element variable="kTAG_DESCRIPTION">
                <item key="en"><![CDATA[CDATA[The <i>global identifier</i> of a user is the user code.]]></item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_CLASS -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:CLASS</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_USER_NAME -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:USER-NAME</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_USER_CODE -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:USER-CODE</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_USER_PASS -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:USER-PASS</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_USER_MAIL -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:USER-MAIL</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_USER_ROLE -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:USER-ROLE</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_USER_PROFILE -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:USER-PROFILE</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_USER_MANAGER -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:USER-MANAGER</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
    
	<!-- kTAG_USER_DOMAIN -->
    <UNIT>
        <EDGE>
            <element variable="kTAG_SUBJECT">:USER-DOMAIN</element>
            <element variable="kTAG_PREDICATE">:ATTRIBUTE-OF</element>
            <element variable="kTAG_OBJECT">:_users</element>
        </EDGE>
    </UNIT>
</ONTOLOGY>
