=== aczepod/PHPWrapper/defines/Ontology.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified">
    
    <!-- ROOT -->
    <xs:element name="ONTOLOGY">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                The ontology is an element container for the list of units.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="UNIT" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- UNIT -->
    <xs:element name="UNIT">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Each unit represents a set of term, node, edge and tag
                instances which define a set of graph related elements.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="TERM">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            List of terms to be instantiated.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="NODE">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            List of nodes to be instantiated.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="EDGE">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            List of edges to be instantiated.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="TAG">
                    <xs:annotation>
                        <xs:documentation xml:lang="en">
                            List of tags to be instantiated.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- TERMS -->
    <xs:element name="TERM">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Term block, should instantiate a single block and can be
                repeated for as many terms need to be defined for the curent block.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="element"/>
            </xs:sequence>
            <xs:attribute name="GID" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Term global identifier, used to reference the term.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="LID" use="required" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Term local identifier.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="NS" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Term namespace as the namespace's term global identifier.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <!-- NODES -->
    <xs:element name="NODE">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Node block, should instantiate a single block and can be
                repeated for as many nodes need to be defined for the curent block.
                Nodes will be identified within the block by the term identifier:
                this means that no two nodes may refer to a term in the same unit.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="element"/>
            </xs:sequence>
            <xs:attribute name="ID" type="xs:ID">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Node identifier, allows referencing homonym term nodes;
                        this attribute has nothing to do with the actual node ID.
                        Use this attribute only if two nodes refer to the same term,
                        or if the node to be referenced is not the node in the current unit.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="class" use="required" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Node class name, this attribute is required.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="term" use="required" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        Term reference, should refer to the global identifier of the term.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <!-- EDGES -->
    <xs:element name="EDGE">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Edge block, should instantiate a single relationship and can be
                repeated for as many edges need to be defined for the curent block.
                Nodes are referenced by their term global identifier, as stated above,
                no two nodes may refer to the same term within the same unit.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="element"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- TAGS -->
    <xs:element name="TAG">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Tag block, should instantiate a single tag, elements of the kTAG_PATH
                must be referenced by term global identifier: if any matching node was instantiated
                within the unit, it will be used instead of the term.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="element"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <!-- Attributes -->
    <xs:element name="element">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Attribute block, each element should define a single property
                or attribute. Array elements should include item elements, scalar
                elements should store the value.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="item"/>
            </xs:sequence>
            <xs:attribute name="tag" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The tag attribute should reference a tag native identifier.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
            <xs:attribute name="variable" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        The variable attribute should reference a tag through the
                        constant name.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <!-- Attribute items -->
    <xs:element name="item">
        <xs:annotation>
            <xs:documentation xml:lang="en">
                Item elements should be used to instantiate array elements,
                use the key attribute if the array uses keys.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" ref="item"/>
            </xs:sequence>
            <xs:attribute name="key" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="en">
                        This attribute should hold the array item index value, only
                        if the array is to be used as an object.
                    </xs:documentation>
                </xs:annotation>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aczepod/PHPWrapper/examples/NODE_INSERT.xml
<?xml version="1.0" encoding="utf-8"?>
<ONTOLOGY
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Library/WebServer/Library/PHPWrapper/defines/Ontology.xsd">
    
	<!-- TEST TERM -->
	
	<UNIT>
    	<NODE class="COntologyMasterVertex" term="TEST">
            <element variable="kTAG_PID">TEST</element>
			<element variable="kTAG_KIND">
				<item>:KIND-FEATURE</item>
			</element>
			<element variable="kTAG_TYPE">
				<item>:TEXT</item>
			</element>
    	</NODE>
	</UNIT>
</ONTOLOGY>

=== aczepod/PHPWrapper/defines/Inputs.xml
<?xml version="1.0" encoding="UTF-8"?>
<ONTOLOGY
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Library/WebServer/Library/PHPWrapper/defines/Ontology.xsd">
        
    <!-- Control -->
    
    <UNIT>
        <TERM NS=":ONTOLOGY:ENUM" LID="CONTROL">
            <element variable="kTAG_LABEL">
                <item key="en">Control</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[<i>Controls</i> are form elements used to display and modify attributes, this category groups all terms that define a display control.]]></item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
            <element variable="kTAG_CATEGORY">
                <item>Enumerated set</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:ENUM</element>
        </EDGE>
    </UNIT>
    
    <!-- INPUT CONTROL ENUMERATIONS -->
    
    <!-- kINPUT_TEXT -->
    <UNIT>
        <TERM NS="" LID="INPUT-TEXT">
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
            <element variable="kTAG_LABEL">
                <item key="en">Text field</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[<i>Text field control</i> allowing input on <i>one line</i> excluding return characters.]]></item>
            </element>
            <element variable="kTAG_SYNONYMS">
                <item>kINPUT_TEXT</item>
                <item>INPUT-TEXT</item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
        	<element variable="kTAG_CATEGORY">
        		<item>Display</item>
        	</element>
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:ENUM:CONTROL</element>
        </EDGE>
    </UNIT>
    
    <!-- kINPUT_TEXTAREA -->
    <UNIT>
        <TERM NS="" LID="INPUT-TEXTAREA">
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
            <element variable="kTAG_LABEL">
                <item key="en">Text area</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[<i>Text area control</i> allowing input on <i>several lines</i> including return characters.]]></item>
            </element>
            <element variable="kTAG_SYNONYMS">
                <item>kINPUT_TEXTAREA</item>
                <item>INPUT-TEXTAREA</item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
        	<element variable="kTAG_CATEGORY">
        		<item>Display</item>
        	</element>
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:ENUM:CONTROL</element>
        </EDGE>
    </UNIT>
    
    <!-- kINPUT_CHOICE -->
    <UNIT>
        <TERM NS="" LID="INPUT-CHOICE">
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
            <element variable="kTAG_LABEL">
                <item key="en">Popup menu</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[<i>Single select group</i> allowing the choice of one item among a list of predefined values.]]></item>
            </element>
            <element variable="kTAG_SYNONYMS">
                <item>kINPUT_CHOICE</item>
                <item>INPUT-CHOICE</item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
        	<element variable="kTAG_CATEGORY">
        		<item>Display</item>
        	</element>
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:ENUM:CONTROL</element>
        </EDGE>
    </UNIT>
    
    <!-- kINPUT_MULTIPLE -->
    <UNIT>
        <TERM NS="" LID="INPUT-MULTIPLE">
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
            <element variable="kTAG_LABEL">
                <item key="en">Combo box</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[<i>Multiple select group</i> allowing the choice of one or more items among a list of predefined values.]]></item>
            </element>
            <element variable="kTAG_SYNONYMS">
                <item>kINPUT_MULTIPLE</item>
                <item>INPUT-MULTIPLE</item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
        	<element variable="kTAG_CATEGORY">
        		<item>Display</item>
        	</element>
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:ENUM:CONTROL</element>
        </EDGE>
    </UNIT>
    
    <!-- kINPUT_RADIO -->
    <UNIT>
        <TERM NS="" LID="INPUT-RADIO">
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
            <element variable="kTAG_LABEL">
                <item key="en">Radio group</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[<i>Radio control group</i> of two controls which allows one of the two to be on. By default this control must return the value of one of the two radios.]]></item>
            </element>
            <element variable="kTAG_SYNONYMS">
                <item>kINPUT_RADIO</item>
                <item>INPUT-RADIO</item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
        	<element variable="kTAG_CATEGORY">
        		<item>Display</item>
        	</element>
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:ENUM:CONTROL</element>
        </EDGE>
    </UNIT>
    
    <!-- kINPUT_CHECKBOX -->
    <UNIT>
        <TERM NS="" LID="INPUT-CHECKBOX">
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
            <element variable="kTAG_LABEL">
                <item key="en">Checkbox control</item>
            </element>
            <element variable="kTAG_DEFINITION">
                <item key="en"><![CDATA[<i>Single checkbox control</i> which can be either selected or not. By default this control must either return a value or not.]]></item>
            </element>
            <element variable="kTAG_SYNONYMS">
                <item>kINPUT_CHECKBOX</item>
                <item>INPUT-CHECKBOX</item>
            </element>
        </TERM>
        <NODE class="COntologyMasterVertex">
        	<element variable="kTAG_CATEGORY">
        		<item>Display</item>
        	</element>
            <element variable="kTAG_KIND">
                <item>:KIND-ENUMERATION</item>
            </element>
        </NODE>
        <EDGE>
            <element variable="kTAG_PREDICATE">:SUBCLASS-OF</element>
            <element variable="kTAG_OBJECT">:ONTOLOGY:ENUM:CONTROL</element>
        </EDGE>
    </UNIT>
</ONTOLOGY>

=== aczepod/PHPWrapper/examples/TERM_MODIFY.xml
<?xml version="1.0" encoding="utf-8"?>
<ONTOLOGY
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/Library/WebServer/Library/PHPWrapper/defines/Ontology.xsd">
    
	<!-- TEST TERM -->
	
	<UNIT>
		<TERM modify="TEST">
			<element variable="kTAG_KIND">
				<item>:KIND-NAMESPACE</item>
				<item>:KIND-PIPPO</item>
			</element>
			<element variable="kTAG_LABEL">
				<item key="en">Test</item>
				<item key="it">Prova</item>
			</element>
		</TERM>
	</UNIT>
</ONTOLOGY>
